[workspace]

members = [
    "injector-example",
    "sabinokaku-loader",
    "sabinokaku-common"
]

[profile.dev]
# Otherwise unhandled exception from .NET is undefined behaviour.
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 'z'
lto = true
codegen-units = 1
strip = 'debuginfo'