[package]
name = "sabinokaku-linux"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
sabinokaku-common = { version = "0.1", path = "../sabinokaku-common" }
[lib]
crate-type=["rlib", "cdylib"]